# Generated by Django 3.2 on 2021-05-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='creditResultDate',
            field=models.DateTimeField(null=True, verbose_name='calculation date'),
        ),
        migrations.AddField(
            model_name='credit',
            name='monthlyInstallment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='credit',
            name='totalAmountRepaid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='CreditResult',
        ),
    ]
