# Generated by Django 3.2 on 2021-05-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditapp', '0002_auto_20210511_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='creditValue',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='credit',
            name='credit_name_text',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='installmentsVal',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='credit',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='credit',
            name='monthlyExpenses',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='credit',
            name='monthlyIncome',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
